config/routes.rb
Rails.application.routes.draw do
  resources :pins

  devise_for :users
  root 'pins#index'
  get "about" => "pages#about" #creates about_path
  get "progress" => "pages#progress" #creates progress_path
  

end

app/models/pin.rb
class Pin < ActiveRecord::Base
		belongs_to :user
		has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
		validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

		validates :image, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_many :pins, dependent: :destroy

   validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

   def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
 end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]


  def index
    @pins = Pin.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 8)
  end

  def show
  end

  def new
    @pin = current_user.pins.build

  end

  def edit
  end

  def create
    @pin = current_user.pins.build(pin_params)
    if @pin.save
      redirect_to @pin, notice: 'Pin was successfully created.' 
    else
      render action: 'new' 
    end
  end

  def update
    if @pin.update(pin_params)
      redirect_to @pin, notice: 'Pin was successfully updated.' 
    else
      render action: 'edit' 
    end
  end

  def destroy
    @pin.destroy
    redirect_to pins_url  
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: "Not authorised to edit this pin" if @pin.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_header.html.erb
	<nav class="navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Pinteresting", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About Us", about_path %></li>
        <li><%= link_to "Progress", progress_path %></li>
        <% if user_signed_in? %>
          <li>
            <%= link_to new_pin_path do %>
              <span class="glyphicon glyphicon-plus"></span> New Pin
            <% end %>
          </li>
          <li><%= link_to "Account Settings", edit_user_registration_path %></li>
          <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign in", new_user_session_path %></li>
        <% end %>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav></br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pinteresting</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width+device-width, initial-scale=1.0">
</head>
<body>

	<%= render 'layouts/header' %>
	<div class="container">
		<% flash.each do |name, msg| %>
		<%= content_tag(:div, msg, class: "alert alert-info") %>
		<% end %>
		<%= yield %>
	</div>
</body>
</html>

app/views/pages/_home.html.erb
<div class="jumbotron center">
	<h1>Welcome to my app!</h1>
		<p>
			<%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
			<%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
		</p>

</div>

app/views/pages/about.html.erb
<div class="jumbotron">
	<h1>About us</h1>
	<p>We are building our first app with One Month Rails.</p>
	<p>Welcome to Pinteresting!</p>
</div>
<div class="well">
	<h2>Our inspiration</h2>
	<blockquote>
  <p>The more that you read, the more things you will know. The more that you learn, the more places you'll go.</p>
  <footer>Dr. Seuss in <cite title="I Can Read With My Eyes Shut!">I Can Read With My Eyes Shut!</cite></footer>
</blockquote>
</div>
<div class="well">
<h2>Our support</h2>
<p>Interested in learning how to do this? Speak to the awesome folk at OneMonth.</p>
<a href="https://onemonth.com" class="btn btn-primary btn-lg active" role="button">Learn more</a>
</div>

app/views/pages/home.html.erb
<div class="jumbotron center">
	<h1>Welcome to my app!</h1>
	<% if user_signed_in? %>
		# do something
	<% else %>
		<p>
			<%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
			<%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
		</p>
	<%end%>

</div>

app/views/pages/progress.html.erb
<div class="jumbotron">
	<h1>Progress</h1>
	<p>In just 30 short days and nights of coding, this app should hopefully be looking pretty sweet. This page is a diary of all the high fives and riptides experienced along the way.</p>
		<div class="progress">
  		<div class="progress-bar" role="progressbar" aria-valuenow="98" aria-valuemin="0" aria-valuemax="100" style="width: 98%;">
    	98%
  		</div>
		</div>
	<div class="panel panel-default">
  	<div class="panel-heading">
    	<h3 class="panel-title">High Fives</h3>
  	</div>
  	<div class="panel-body">
    <p>1 September - joining <%= link_to "OneMonth", "https://onemonth.com"%> and taking the <%= link_to "plunge", "https://www.youtube.com/watch?v=kP7w1XYqq0M" %>!</p>
    <p>3 September - joining <%= link_to "GitHub", "https://github.com/" %>.</p>
    <p>6 September - discovering <%= link_to "Flat UI Colours", "http://flatuicolors.com/" %>.</p>
    <p>7 September - live via <%= link_to "Heroku", "http://heroku.com" %>!</p>
    <p>9 September - past the halfway mark!</p>
    <p>11 September - learned that MVC isn't just a games industry trade magazine...</p>
    <p>14 September - added images with paperclip :)</p>
    <p>16 September - building with <%= link_to "jQuery masonry", "http://masonry.desandro.com/" %> for the first time!</p>
    <p>20 September - added names and validations, almost there...</p>
  	</div>
	</div>
	<div class="panel panel-default">
  	<div class="panel-heading">
    	<h3 class="panel-title">Riptides</h3>
  	</div>
  	<div class="panel-body">
    <p>6 September - broken image thumbnails building the progress page :(</p>
    <p>7 September - old devise version led to bcrypt warning / mini stumble.</p>
    <p>14 September - nokogiri gem install error meltdown. Found a simple solution in the <%= link_to "community pages", "http://community.onemonth.com/t/what-was-the-hardest-part-about-one-month-rails/14/4" %> though.</p>
  	</div>
	</div>
</div>

app/views/pins/_form.html.erb
<%= form_for @pin, html: { multipart: true } do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<%= render 'pages/home' unless user_signed_in? %>

<div id="pins" class="transitions-enabled">
  <% @pins.each do |pin| %>
    <div class="box panel panel-default">
      <%= link_to image_tag(pin.image.url(:medium)), pin %>
      <div class="panel-body">
        <p><%= pin.description %></p>
        <p><strong><%= pin.user.name if pin.user %></strong></p>
        <% if pin.user == current_user %>
        <div class="actions">
          <%= link_to edit_pin_path(pin) do %>
            <span class="glyphicon glyphicon-edit"></span> Edit
          <% end %>
          <%= link_to pin, method: :delete, data: { confirm: 'Are you sure?' } do %>
            <span class="glyphicon glyphicon-trash"></span> Delete
          <% end %>
        </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<div class="center">
  <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
</div>

app/views/pins/new.html.erb
<h1>New pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<%= link_to 'Back', pins_path %>

<div class="row">
	<div class="col-md-offset-2 col-md-8">
		<div class="panel panel-default">
		<div class="panel-heading center">
		<%= image_tag @pin.image.url(:medium) %>
		</div> 
		<div class="panel-body">
		<p><%= @pin.description %></p>
		<p><strong><%= @pin.user.name if @pin.user %></strong></p>

		<% if @pin.user == current_user %>
			<%= link_to edit_pin_path(@pin) do %> 
				<span class="glyphicon glyphicon-edit"></span> Edit
			<% end %>
		<% end %>
		</div>
	</div>

</div>